//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.AccessData.Models.Admin
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BiteccoEntities : DbContext
    {
        public BiteccoEntities()
            : base("name=BiteccoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SYS_Control> SYS_Control { get; set; }
        public virtual DbSet<SYS_Grid> SYS_Grid { get; set; }
        public virtual DbSet<SYS_Menu> SYS_Menu { get; set; }
        public virtual DbSet<SYS_SubMenu> SYS_SubMenu { get; set; }
        public virtual DbSet<SYS_Toolbar> SYS_Toolbar { get; set; }
        public virtual DbSet<SYS_Tree> SYS_Tree { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<SYS_Form> SYS_Form { get; set; }
    }
}
