//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.AccessData.Models.Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_Tree
    {
        public int ID_SYS_Tree { get; set; }
        public int ID_Form { get; set; }
        public string NameTree { get; set; }
        public string TextValue { get; set; }
        public string IdValue { get; set; }
        public string ChildValue { get; set; }
        public string ApiName { get; set; }
    }
}
