//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.AccessData.Models.Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_Form
    {
        public int ID_SYS_Form { get; set; }
        public string NameForm { get; set; }
        public Nullable<int> LabelWidth { get; set; }
        public Nullable<int> InputWidth { get; set; }
        public string ApiNameConfig { get; set; }
        public string ApiNameControl { get; set; }
        public string ApiData { get; set; }
        public string ApiNameToolbar { get; set; }
        public string ApiListData { get; set; }
        public string HelpForm { get; set; }
    }
}
