//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.AccessData.Models.Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_Menu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SYS_Menu()
        {
            this.SYS_Menu1 = new HashSet<SYS_Menu>();
        }
    
        public int ID_SYS_Menu { get; set; }
        public string ControllerName { get; set; }
        public string ActionMethod { get; set; }
        public string MenuName { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<long> CreateBy { get; set; }
        public Nullable<bool> IsCache { get; set; }
        public string Status { get; set; }
        public Nullable<int> ID_SYS_Menu_Parent { get; set; }
        public string OrderBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYS_Menu> SYS_Menu1 { get; set; }
        public virtual SYS_Menu SYS_Menu2 { get; set; }
    }
}
