//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.AccessData.Models.Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_Control
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SYS_Control()
        {
            this.SYS_Control1 = new HashSet<SYS_Control>();
        }
    
        public int ID_SYS_Control { get; set; }
        public int ID_Form { get; set; }
        public string LabelControl { get; set; }
        public string NameControl { get; set; }
        public string TypeControl { get; set; }
        public string Status { get; set; }
        public string OrderBy { get; set; }
        public Nullable<int> ID_SYS_Control_Parent { get; set; }
        public Nullable<int> WidthControl { get; set; }
        public string ApiName { get; set; }
        public string DisplayText { get; set; }
        public string ValueText { get; set; }
        public string ValueChild { get; set; }
        public Nullable<bool> ValueDisable { get; set; }
        public Nullable<bool> ValueRequired { get; set; }
        public string ValueValidate { get; set; }
        public string ValueDateFormat { get; set; }
        public string ValueServerDateFormat { get; set; }
        public string ValueNumberFormat { get; set; }
        public Nullable<int> ValueMaxLength { get; set; }
        public Nullable<int> HeightControl { get; set; }
        public Nullable<int> ID_Action { get; set; }
        public string XML_Link { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYS_Control> SYS_Control1 { get; set; }
        public virtual SYS_Control SYS_Control2 { get; set; }
    }
}
