//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.AccessData.Models.Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_Grid
    {
        public int ID_SYS_Grid { get; set; }
        public int ID_Form { get; set; }
        public string NameColumn { get; set; }
        public string MemberColumn { get; set; }
        public string TypeColumn { get; set; }
        public string WidthColumn { get; set; }
        public string AlignHeader { get; set; }
        public string AlignColumn { get; set; }
        public string OrderBy { get; set; }
        public string ApiName { get; set; }
    }
}
