//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.AccessData.Models.Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_Toolbar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SYS_Toolbar()
        {
            this.SYS_Toolbar1 = new HashSet<SYS_Toolbar>();
        }
    
        public int ID_SYS_Toolbar { get; set; }
        public string ToolbarType { get; set; }
        public string ToolbarText { get; set; }
        public string ToolbarImage { get; set; }
        public string ToolbarDisImage { get; set; }
        public string ToolbarAction { get; set; }
        public Nullable<int> ID_Form { get; set; }
        public Nullable<int> ID_SYS_Toolbar_Parent { get; set; }
        public string OrderBy { get; set; }
        public string ToolbarName { get; set; }
        public Nullable<bool> DisableItem { get; set; }
        public Nullable<bool> EnableItem { get; set; }
        public string Language { get; set; }
        public Nullable<int> ID_Action { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYS_Toolbar> SYS_Toolbar1 { get; set; }
        public virtual SYS_Toolbar SYS_Toolbar2 { get; set; }
    }
}
